# Generated by Django 4.2.7 on 2023-12-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0002_rename_title_team_name_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="country",
            field=models.CharField(
                choices=[("usa", "USA"), ("korea", "Korea"), ("japan", "Japan")],
                default="korea",
                max_length=5,
            ),
        ),
    ]
